language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod install --project-directory=PPEventRegistryAPI

branches:
  only:
    - master

notifications:
  email: false

env:
  global:
  - WORKSPACE=PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace
  - SCHEME=PPEventRegistry
  - IOS_SDK=iphonesimulator10.0
  - WATCHOS_SDK=watchsimulator3.0
  - TVOS_SDK=appletvsimulator10.0

matrix:
  - DESTINATION="name=iPhone 6s,OS=10.0"         SDK="$IOS_SDK"
  - DESTINATION="name=Apple Watch - 42mm,OS=3.0" SDK="$WATCHOS_SDK"
  - DESTINATION="name=Apple TV 1080p,OS=10.0"    SDK="$TVOS_SDK"

script:
- set -o pipefail
- xcodebuild build-for-testing test-without-building -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash)
