language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod install --project-directory=PPEventRegistryAPI

notifications:
  email: false

script:
- xcodebuild test -workspace PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace -scheme PPEventRegistryAPI -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0” CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
