language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod install --project-directory=PPEventRegistryAPI

notifications:
  email: false

script:
- xcodebuild -workspace 'PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace' -scheme 'PPEventRegistryAPI' -configuration Debug build test -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6s,OS=10.0"
