language: Objective-C

osx_image: xcode8

before_install:
- bundle
- pod install --project-directory=PPEventRegistryAPI

script:
  xctool
  -workspace PPEventRegistryAPI/PPEventRegistryAPI.xcworkspace
  -scheme PPEventRegistryAPI
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6s,OS=10.0'
  build
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
